apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: dev-istiocontrolplane
spec:
  profile: default
  revision: 1-6-8
  tag: 1.6.8
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 2
        service:
          ports:
            - name: http2
              port: 80
              nodePort: 31380
            - name: https
              port: 443
              nodePort: 31390
    pilot:
      k8s:
        hpaSpec:
          minReplicas: 2
        resources:
          requests:
            memory: 3072M
            cpu: 100m
    
  addonComponents:
    tracing:
      enabled: true
    prometheus:
      enabled: true
    grafana:
      enabled: true

  values:
    gateways:
      istio-ingressgateway:
        name: istio-ingressgateway
        type: NodePort
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128M
          limits:
            cpu: 2000m
            memory: 1024M
      proxy_init:
        resources:
          limits:
            cpu: 100m
            memory: 50M
          requests:
            cpu: 10m
            memory: 10M